### ISSUE TITLE
[徵求]想在11/10實作的RNN/LSTM主題？

### ISSUE THREAD

**Issue by Lhwei** [WomenWhoCodeTaipei/DeepLearningwithPython#7]
大家有任何想法都可以在下面留言，
如果有資料要提供，請附上可下載的連結！

**Comment by tcglarry** [comment]
希望可以聽到 
a. 文字前處理的技巧. 
b. pre-trained model vs non-pretrained model (中文例子最好) 
c. RNN, CNN and attention 的不同結果比較. 

Tks *2 (1 for last meet up, 1 for this up coming one) 
Larry

**Comment by gomaxlou** [comment]
產生及辨別假新聞
